# Generated by Django 3.2.16 on 2022-12-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
    ]
