# Generated by Django 3.2.16 on 2022-12-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='captcha')),
                ('email', models.EmailField(max_length=35, verbose_name='email')),
                ('send_type', models.CharField(choices=[('register', 'reg'), ('forget', 'for')], default='register', max_length=20)),
            ],
            options={
                'verbose_name': 'email captha',
                'verbose_name_plural': 'email captha',
            },
        ),
    ]
