# Generated by Django 3.2.16 on 2022-12-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='personal_description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='personal_motto'),
        ),
    ]
