# Generated by Django 3.2.16 on 2022-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221203_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='personal_motto'),
        ),
    ]
