# Generated by Django 3.2.16 on 2022-12-04 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modifiy_time')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modifiy_time')),
            ],
            options={
                'verbose_name': 'Post Tag',
                'verbose_name_plural': 'Post Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=61, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', max_length=200, verbose_name='abstract')),
                ('content', models.TextField(verbose_name='content')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modifiy_time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
