# Generated by Django 3.2.16 on 2022-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'search'), (2, 'newest'), (3, 'hotest'), (4, 'recent comment'), (5, 'archive blog'), (6, 'HTML')], default=1, verbose_name='displayType')),
                ('content', models.CharField(blank=True, default='', help_text='can be null if not HTML', max_length=500, verbose_name='content')),
                ('sort', models.PositiveIntegerField(default=1, help_text='sortbyid', verbose_name='sort')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Hide'), (2, 'Show')], default=2, verbose_name='status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='publishTime')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
                'ordering': ['-sort'],
            },
        ),
    ]
