# Generated by Django 3.2.16 on 2022-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_counts',
            field=models.IntegerField(default=0, verbose_name='view_counts'),
        ),
    ]
