# Generated by Django 3.2.16 on 2022-12-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content'),
        ('blog', '0008_alter_comment_options'),
    ]

    operations = [
    ]
